language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: 
   - python manage.py test polls  --settings=mysite.travis_settings
   - python manage.py test authdetails  --settings=mysite.travis_settings
   - python manage.py test_coverage polls authdetails polls_graphos
after_success:
  - coveralls