language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: 
   - python manage.py test polls  --settings=mysite.travis_settings
   - python manage.py test authdetails  --settings=mysite.travis_settings
   - coverage run --source=coveralls,polls,authdetails,polls_graphos  manage.py test
after_success:
  - coveralls